### ISSUE TITLE
Fully Document Everything

### ISSUE THREAD

**Issue by azenla** [SpinlockLabs/github.dart#3]
## Description

We need to document EVERYTHING.
## Assistants

@TrainerGuy22
## Tasks
- [x] Document GitHub Class
- [x] Document Model Objects
- [x] Document Dates Helper
- [x] Document Utility Library
- [x] Document Development Process
